name: Build and push Docker image to dockerhub

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

#    - name: Extract metadata (tags, labels) for Docker
#      id: meta
#      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#      with:
#        images: ${{ env.IMAGE_NS}}/${{ env.IMAGE_NAME }}
#
#    - name: debug
#      run: echo "::notice ${{ steps.meta.outputs.tags }}"

    - name: debug
      run: echo "::notice REG=${{ env.REGISTRY }} IMG=${{ env.IMAGE_NAME }}"

    - name: Build and push to dockerhub
      id: push
      uses: docker/build-push-action@v5
      with:
       context: .
       push: true
       tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
#       tags: ${{ steps.meta.outputs.tags }}
#       labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
